#!/bin/bash

# Comment this line if you want to always concatenate the branch name when it is missing.
# This line will avoid the rebase message changes that is a little annoying.
if [ -n "$COMMIT_MSG_FILE" ];then return; fi 

COMMIT_MSG_FILE=$1
BRANCH_NAME=$(git symbolic-ref --short HEAD | sed 's/\(.*-[0-9][0-9]*\).*/\1/')
BRANCH_NAME="${BRANCH_NAME##*/}"

if [ -n "$BRANCH_NAME" ] &&
   [ -z "$(head -1 ${COMMIT_MSG_FILE})" ]
then
  sed -i.bak -e "1s/^/\fix(${BRANCH_NAME}\): \n\
# Please, use semantic release build|ci|docs|feat|fix|perf|refactor|test syntax.\n\
# https://github.com/semantic-release/semantic-release?tab=readme-ov-file#commit-message-format/;" ${COMMIT_MSG_FILE}
fi
